HTTP/1.1 200 OK
Content-Type: application/vnd.api+json

{
  "links": {
    "self": "/document_types/1/relationships/people",
    "related": "/document_types/1/people"
  },
  "data": [{
    "type": "people",
    "id": "00027855859"
  },
  {
    "type": "people",
    "id": "00031988189"
  }]
}
